const Config = {
    REACT_APP_SITE_TITLE: 'TITLE',
    ENV_BACKEND_BASE_URL: 'BACKEND_BASE_URL',
    ENV_BACKEND_API_PATH: 'BACKEND_API_PATH',
    ENV_BASE_NAME: 'BASE_NAME',
    ENV_DICOM_VIEWER_PAGE: 'DICOM_VIEWER_PAGE',
    ENV_DICOM_SERVER_PATH: 'DICOM_SERVER_PATH',
    ENV_TIMEZONE_OFFSET: 'TIMEZONE_OFFSET'
}

export default Config;