name: Master build

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set env
        run: echo "RELEASE_VERSION=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV
      - name: NCG Docker Registry
        env:
          DOCKER_REGISTRY_URL: docker.io
          NCG_PASSWORD: ${{ secrets.DOCKER_NCG_PASSWORD }}
          NCG_USERNAME: ${{ secrets.DOCKER_NCG_USERNAME }}
        run: docker login -u $NCG_USERNAME -p $NCG_PASSWORD $DOCKER_REGISTRY_URL
      - name: Build docker image for NCG
        env:
          CONTAINER_REPO_NAME: hiu-ui
          NCG_USERNAME: ${{ secrets.DOCKER_NCG_USERNAME }}
        run: docker build --build-arg BACKEND_BASE_URL=https://ndhm-dev.bahmni-covid19.in/ --build-arg BASE_NAME=/hiu --build-arg BACKEND_API_PATH=hiu-api --build-arg DICOM_SERVER_PATH=/dicom-web --build-arg VIEWER_PAGE=/viewer/ --build-arg TITLE=BahmniHIU -t $NCG_USERNAME/$CONTAINER_REPO_NAME:$RELEASE_VERSION .
      - name: Push Docker image to NCG Registry
        env:
          CONTAINER_REPO_NAME: hiu-ui
          NCG_USERNAME: ${{ secrets.DOCKER_NCG_USERNAME }}
        run: docker push $NCG_USERNAME/$CONTAINER_REPO_NAME:$RELEASE_VERSION
      - name: Tag Docker Container with latest tag
        env:
          CONTAINER_REPO_NAME: hiu-ui
          DOCKER_USERNAME: ${{ secrets.DOCKER_NCG_USERNAME }}
        run: docker tag $DOCKER_USERNAME/$CONTAINER_REPO_NAME:$RELEASE_VERSION $DOCKER_USERNAME/$CONTAINER_REPO_NAME:latest
      - name: Push Latest Docker Container to Registry
        env:
          CONTAINER_REPO_NAME: hiu-ui
          DOCKER_USERNAME: ${{ secrets.DOCKER_NCG_USERNAME }}
        run: docker push $DOCKER_USERNAME/$CONTAINER_REPO_NAME:latest
